### ISSUE TITLE
Error converting value "received" to type 'CakeMail.RestClient.Models.LogType'

### ISSUE THREAD

**Issue by MinaMessi** [Jericho/CakeMail.RestClient#52]
I got an issue while trying to call CakeMailApi.Mailings.GetLogsAsync.

"Requested value 'received' was not found.
[JsonSerializationException: Error converting value "received" to type 'CakeMail.RestClient.Models.LogType'. Path 'data.logs[2].action', line 1, position 1121.]"

It seems that there is a response value which is not listed in the enum LogType.
So we need to add this missing value into the enum.

![exception](https://user-images.githubusercontent.com/15873990/55177376-c6da2580-518b-11e9-9dbc-e49e42e5be99.jpg)

**Comment by Jericho** [comment]
This is interesting. I wonder if this is a new log type CakeMail recently added.

Anyway, I'll add it to the enum to avoid this exception.

**Comment by MinaMessi** [comment]
Thank you for looking in to this.  I'm willing to contribute to this issue myself, as I understand you may be busy with other projects.

**Comment by MinaMessi** [comment]
> This is interesting. I wonder if this is a new log type CakeMail recently added.
> 
> Anyway, I'll add it to the enum to avoid this exception.

Ok thanks!

**Comment by Jericho** [comment]
pushing v0.8.3 to NuGet. Will be available shortly.
